main: com.alvarlagerlof.quake2.Main
name: Quake2
version: 0.1
api-version: 1.14
commands:
  quake:
    description: Quake2
    aliases:
      - q
    permission: quake.admin
    permission-message: You do not have permission!
    usage: /<quake>
  quakesetup:
    description: Quake2 Setup
    aliases:
      - qsetup
      - qs
    permission: quake.admin
    permission-message: You do not have permission!
    usage: /<quakesetup>
permissions:
  quake.admin:
    description: Allows all commands
    default: op